AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/FileName:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
Style/SignalException:
  Enabled: false
